services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  _instanceof:
    Twig\Extension\ExtensionInterface:
      tags: ['twig.extension']

  # Twig
  twig:
    class: Timber\Timber

  Timber\Timber: '@twig'

  Timber\Loader:
    class: Timber\Loader

  # Настоящий, т.е. Twig\Environment инстанц Твига.
  twig.instance:
    class: Twig\Environment
    factory: ['@Timber\Loader', 'get_twig']

  Twig\Environment: '@twig.instance'

  # Конфигурация Твига.
  twig.config:
    class: Prokl\TimberTwigBundle\Services\TwigConfig
    arguments:
      - '@parameter_bag'

  Prokl\TimberTwigBundle\Services\TwigConfig: '@twig.config'

  twig.extension:
    class: Prokl\TimberTwigBundle\Services\TwigExtensions
    arguments: ['@twig.config', '@service_container']

  Prokl\TimberTwigBundle\Services\TwigExtensions: '@twig.extension'

  twig.extension.init.hook:
    class: Prokl\TimberTwigBundle\Services\TwigExtensions
    factory: ['@twig.extension', 'hooksInit']
    tags: ['service.bootstrap']

  twig_configurator:
    class: Prokl\TimberTwigBundle\Services\TwigConfiguratorWordpress
    arguments: ['@parameter_bag', '@twig']

  twig_configurator.templates_location:
    class: Prokl\TimberTwigBundle\Services\TwigConfiguratorWordpress
    factory: ['@twig_configurator', 'pathTemplates']

  # Прокси к Тимберу (для миграции на следующую версию).
  timber_proxy:
    class: Prokl\TimberTwigBundle\Services\Proxy\TimberProxy

  Prokl\TimberTwigBundle\Services\Proxy\TimberProxy: '@timber_proxy'
  Prokl\TimberTwigBundle\Services\Proxy\Contract\TimberProxyInterface: '@timber_proxy'

  # Инициализация Тимбера путями к шаблонам из конфигов.
  timber_init:
    class: Prokl\TimberTwigBundle\Services\Proxy\TimberProxy
    factory: ['@timber_proxy', 'setLocations']
    arguments: ['@twig_configurator.templates_location']
    tags: ['service.bootstrap']

  # Template cache warmer
  Prokl\TimberTwigBundle\Services\TemplateCacheWarmer:
    autoconfigure: false
    arguments:
      - '@twig.instance'
    class: Prokl\TimberTwigBundle\Services\TemplateCacheWarmer
    tags: [kernel.cache_warmer]