services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  _instanceof:
    Twig\Extension\ExtensionInterface:
      tags: ['twig.extension']

    Twig\Loader\LoaderInterface:
      tags: [ 'twig.loader' ]

    Twig\Extension\RuntimeExtensionInterface:
      tags: [ 'twig.runtime' ]

  twig: '@twig.instance'

  # Инстанц Твига.
  twig.instance:
    class: Twig\Environment
    factory: ['@twig.service', 'instance']

  Twig\Environment: '@twig.instance'

  # Twig loader
  twig.loader:
    class: Twig\Loader\FilesystemLoader
    arguments:
      - '@twig_configurator.templates_location'

  twig.service:
    class: Prokl\TimberTwigBundle\Services\TwigService
    arguments:
      - '@twig.loader'
      - '%kernel.debug%'
      - '%twig_cache_dir%'
      - '%twig_config%'
    calls:
      - setContainer: ['@service_container']

  # Подхват Twig extensions
  twig_initializer:
    class: Prokl\TimberTwigBundle\Services\TwigInitializer
    arguments:
      - '@twig.instance'
      - !tagged_iterator twig.extension

  twig.extension.init.hook:
    class: Prokl\TimberTwigBundle\Services\TwigInitializer
    factory: ['@twig_initializer', 'applyFunctions']
    arguments: ['@twig_function_config']
    tags:
      - { name: 'service.bootstrap', priority: 100}

  twig_initializer_bootstrap:
    class: Prokl\TimberTwigBundle\Services\TwigInitializer
    factory: ['@twig_initializer', 'applyExtensions']
    tags:
      - { name: 'service.bootstrap', priority: 200}

  # Конфигурация Твига.
  twig.config:
    class: Prokl\TimberTwigBundle\Services\TwigConfig
    arguments:
      - '@parameter_bag'

  Prokl\TimberTwigBundle\Services\TwigConfig: '@twig.config'

  twig.extension:
    class: Prokl\TimberTwigBundle\Services\TwigExtensions
    arguments: ['@twig.config', '@service_container']

  twig_function_config:
    class: Prokl\TimberTwigBundle\Services\TwigExtensions
    factory: ['@twig.extension', 'functions']

  twig_configurator:
    class: Prokl\TimberTwigBundle\Services\TwigConfiguratorWordpress
    arguments: ['@parameter_bag']

  twig_configurator.templates_location:
    class: Prokl\TimberTwigBundle\Services\TwigConfiguratorWordpress
    factory: ['@twig_configurator', 'pathTemplates']

  # Template cache warmer
  Prokl\TimberTwigBundle\Services\TemplateCacheWarmer:
    autoconfigure: false
    arguments:
      - '@twig.instance'
    class: Prokl\TimberTwigBundle\Services\TemplateCacheWarmer
    tags: [kernel.cache_warmer]
