services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  _instanceof:
    Twig\Extension\ExtensionInterface:
      tags: ['twig.extension']

  # Подхват Twig extensions
  twig_initializer:
    class: Prokl\TimberTwigBundle\Services\TwigInitializer
    arguments:
      - '@twig.instance'
      - !tagged_iterator twig.extension

  # Инициализация Тимбера путями к шаблонам из конфигов.
  timber_init:
    class: Prokl\TimberTwigBundle\Services\Proxy\TimberProxy
    factory: ['@timber_proxy', 'setLocations']
    arguments: ['@twig_configurator.templates_location']
    tags:
      - { name: 'service.bootstrap', priority: 100}

  twig.extension.init.hook:
    class: Prokl\TimberTwigBundle\Services\TwigExtensions
    factory: ['@twig_initializer', 'applyFunctions']
    arguments: ['@twig_function_config']
    tags:
      - { name: 'service.bootstrap', priority: 200}

  twig_initializer_bootstrap:
    class: Prokl\TimberTwigBundle\Services\TwigInitializer
    factory: ['@twig_initializer', 'applyExtensions']
    tags:
      - { name: 'service.bootstrap', priority: 300}

  # Twig
  twig:
    class: Timber\Timber

  Timber\Timber: '@twig'

  Timber\Loader:
    class: Timber\Loader

  # Настоящий, т.е. Twig\Environment инстанц Твига.
  twig.instance:
    class: Twig\Environment
    factory: ['@Timber\Loader', 'get_twig']

  Twig\Environment: '@twig.instance'

  # Конфигурация Твига.
  twig.config:
    class: Prokl\TimberTwigBundle\Services\TwigConfig
    arguments:
      - '@parameter_bag'

  Prokl\TimberTwigBundle\Services\TwigConfig: '@twig.config'

  twig.extension:
    class: Prokl\TimberTwigBundle\Services\TwigExtensions
    arguments: ['@twig.config', '@service_container', '@twig_initializer']

  twig_function_config:
    class: Prokl\TimberTwigBundle\Services\TwigExtensions
    factory: ['@twig.extension', 'functions']

  twig_configurator:
    class: Prokl\TimberTwigBundle\Services\TwigConfiguratorWordpress
    arguments: ['@parameter_bag', '@twig']

  twig_configurator.templates_location:
    class: Prokl\TimberTwigBundle\Services\TwigConfiguratorWordpress
    factory: ['@twig_configurator', 'pathTemplates']

  # Прокси к Тимберу (для миграции на следующую версию).
  timber_proxy:
    class: Prokl\TimberTwigBundle\Services\Proxy\TimberProxy

  Prokl\TimberTwigBundle\Services\Proxy\TimberProxy: '@timber_proxy'
  Prokl\TimberTwigBundle\Services\Proxy\Contract\TimberProxyInterface: '@timber_proxy'

  # Тимберовский глобальный контекст.
  timber_context:
    class: Prokl\TimberTwigBundle\Services\Proxy\TimberProxy
    factory: ['@timber_proxy', 'getContext']

  # Template cache warmer
  Prokl\TimberTwigBundle\Services\TemplateCacheWarmer:
    autoconfigure: false
    arguments:
      - '@twig.instance'
    class: Prokl\TimberTwigBundle\Services\TemplateCacheWarmer
    tags: [kernel.cache_warmer]

  # Twig loader
#  twig.native.loader:
#    class: Twig\Loader\FilesystemLoader
#    arguments:
#      - '%twig_paths%'
#
#  twig.service:
#    class: Prokl\TimberTwigBundle\Services\TwigService
#    arguments:
#      - '@twig.loader'
#      - '%debug%'
#      - '%twig_cache_dir%'
#      - '%twig_config%'